keys:
  # Personal key (for editing secrets on workstation)
  - &admin age1372w738lz7vnw0cjteaw5dd63stg4r3rne70340zrknr0ccxt5ns7dr7vw

  # Host keys (derived from SSH host keys via ssh-to-age)
  - &kryses-tyr age16sn75vz269mp7j6red3y3h8mnw0u5rr3zrj09a9mg5atpeek4gusrqddxd
  - &kryses-brokkr age1shhve703c2hlr63a67xzll2k5khp22zxhz0auqff3q9qcdyn0d4qhpp4lp

creation_rules:
  - path_regex: ^secrets/secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *kryses-tyr
          - *kryses-brokkr
