# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."ayon-postgres" = {
    image = "postgres:15";
    environment = {
      "POSTGRES_DB" = "ayon";
      "POSTGRES_PASSWORD" = "ayon";
      "POSTGRES_USER" = "ayon";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "ayon_db:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U ayon"
      "--health-interval=5s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=postgres"
      "--network=ayon_default"
    ];
  };
  systemd.services."podman-ayon-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ayon_default.service"
      "podman-volume-ayon_db.service"
    ];
    requires = [
      "podman-network-ayon_default.service"
      "podman-volume-ayon_db.service"
    ];
    partOf = [
      "podman-compose-ayon-root.target"
    ];
    wantedBy = [
      "podman-compose-ayon-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ayon-redis" = {
    image = "redis:alpine";
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=redis-cli ping | grep PONG"
      "--health-interval=5s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=redis"
      "--network=ayon_default"
    ];
  };
  systemd.services."podman-ayon-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ayon_default.service"
    ];
    requires = [
      "podman-network-ayon_default.service"
    ];
    partOf = [
      "podman-compose-ayon-root.target"
    ];
    wantedBy = [
      "podman-compose-ayon-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ayon-server" = {
    image = "ynput/ayon:latest";
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/home/kryses/documents/work/ayon-workspace/repos/ayon-docker/addons:/addons:rw"
      "/home/kryses/documents/work/ayon-workspace/repos/ayon-docker/storage:/storage:rw"
    ];
    ports = [
      "5000:5000/tcp"
    ];
    dependsOn = [
      "ayon-postgres"
      "ayon-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"curl\", \"-f\", \"http://localhost:5000/api/info\"]"
      "--health-interval=10s"
      "--health-retries=3"
      "--health-timeout=2s"
      "--network-alias=server"
      "--network=ayon_default"
    ];
  };
  systemd.services."podman-ayon-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ayon_default.service"
    ];
    requires = [
      "podman-network-ayon_default.service"
    ];
    partOf = [
      "podman-compose-ayon-root.target"
    ];
    wantedBy = [
      "podman-compose-ayon-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-ayon_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f ayon_default";
    };
    script = ''
      podman network inspect ayon_default || podman network create ayon_default
    '';
    partOf = [ "podman-compose-ayon-root.target" ];
    wantedBy = [ "podman-compose-ayon-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-ayon_db" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect ayon_db || podman volume create ayon_db
    '';
    partOf = [ "podman-compose-ayon-root.target" ];
    wantedBy = [ "podman-compose-ayon-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-ayon-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
