#!/bin/bash
scp root@192.168.1.224:/usr/share/doc/taskd/pki/kryses.cert.pem ~/.task
scp root@192.168.1.224:/usr/share/doc/taskd/pki/kryses.key.pem ~/.task
scp root@192.168.1.224:/usr/share/doc/taskd/pki/ca.cert.pem ~/.task
